"""
Generate a PLACEHOLDER NetCDF temperature dataset for the Bay of Bengal.

This is SYNTHETIC data. It is physically plausible (realistic SST range, a
mixed layer, a thermocline, a couple of mesoscale eddies) but it is NOT a real
INCOIS / Copernicus product. It exists so the whole pipeline can be built and
tested; swap in a real NetCDF file with the same dimension names and the rest
of the stack keeps working unchanged.

Output: backend/data/ocean_temp.nc
Dims:   time, depth, lat, lon   (CF-ish, depth positive down, units degC)
"""

import numpy as np
import xarray as xr
from pathlib import Path

OUT = Path(__file__).parent / "ocean_temp.nc"

# Bay of Bengal bounding box
LAT_MIN, LAT_MAX = 5.0, 22.0
LON_MIN, LON_MAX = 80.0, 95.0
RES = 0.1

DEPTHS = np.array([0.0, 50.0, 100.0, 200.0, 500.0, 1000.0], dtype="float32")
N_TIME = 4  # 4 daily steps; time animation is out of scope for the prototype


def surface_field(lat2d, lon2d, t):
    """Plausible Bay of Bengal SST field, degC."""
    # Warm pool in the south, cooler toward the northern head of the bay.
    base = 29.4 - 0.14 * (lat2d - LAT_MIN)

    # Weak zonal gradient (slightly cooler along the western boundary).
    base -= 0.05 * (LON_MAX - lon2d) * 0.3

    # Coastal upwelling strip along the east Indian coast (western edge).
    coast = np.exp(-((lon2d - 81.0) ** 2) / 2.0) * np.exp(-((lat2d - 15.0) ** 2) / 40.0)
    base -= 1.2 * coast

    # Two mesoscale eddies, drifting slowly with timestep.
    drift = 0.25 * t
    warm = np.exp(-(((lat2d - 13.0) ** 2) / 3.0 + ((lon2d - 87.5 - drift) ** 2) / 3.0))
    cold = np.exp(-(((lat2d - 9.0) ** 2) / 2.5 + ((lon2d - 91.0 + drift) ** 2) / 2.5))
    base += 1.1 * warm - 1.4 * cold

    # Fine-scale texture so the rendered plane does not look flat.
    base += 0.25 * np.sin(lat2d * 1.7 + t) * np.cos(lon2d * 1.9 - t)

    # Slight day-to-day warming trend.
    base += 0.08 * t
    return base


def build():
    lats = np.arange(LAT_MIN, LAT_MAX + RES / 2, RES, dtype="float32")
    lons = np.arange(LON_MIN, LON_MAX + RES / 2, RES, dtype="float32")
    lon2d, lat2d = np.meshgrid(lons, lats)

    mld = 40.0      # mixed layer depth, m
    t_deep = 4.0    # asymptotic deep temperature, degC
    scale = 250.0   # thermocline e-folding scale, m

    data = np.empty((N_TIME, DEPTHS.size, lats.size, lons.size), dtype="float32")
    for ti in range(N_TIME):
        sst = surface_field(lat2d, lon2d, ti)
        for zi, z in enumerate(DEPTHS):
            if z <= mld:
                layer = sst - 0.01 * z
            else:
                layer = t_deep + (sst - t_deep) * np.exp(-(z - mld) / scale)
            data[ti, zi] = layer

    times = np.array(
        ["2024-03-01", "2024-03-02", "2024-03-03", "2024-03-04"], dtype="datetime64[ns]"
    )

    ds = xr.Dataset(
        {
            "temperature": (
                ("time", "depth", "lat", "lon"),
                data,
                {
                    "units": "degC",
                    "long_name": "sea_water_potential_temperature",
                    "standard_name": "sea_water_potential_temperature",
                },
            )
        },
        coords={
            "time": times,
            "depth": ("depth", DEPTHS, {"units": "m", "positive": "down"}),
            "lat": ("lat", lats, {"units": "degrees_north"}),
            "lon": ("lon", lons, {"units": "degrees_east"}),
        },
        attrs={
            "title": "OceanScope prototype placeholder temperature field",
            "source": "SYNTHETIC - generated by generate_sample.py, not observational data",
            "region": "Bay of Bengal",
            "Conventions": "CF-1.8",
        },
    )

    ds.to_netcdf(OUT, engine="netcdf4")
    print(f"wrote {OUT}  shape={data.shape}  range={data.min():.2f}..{data.max():.2f} degC")


if __name__ == "__main__":
    build()
